### ISSUE TITLE
Rename repo to karmakurier.org

### ISSUE THREAD

**Issue by zugende** [karmakurier/karmakurier.org#1]
At the moment  when someone clones this repo he only sees "web" as folder name. I recommend renaming the repo to "karmakurier.org" similiar as the NodeJS organisation is doing it.
![image](https://user-images.githubusercontent.com/7976502/77540037-b47bf000-6ea2-11ea-90f1-8dc2bbc18778.png)

**Comment by fjw** [comment]
gute idee. mach ich
